### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by Boscop** [slamdata/purescript-halogen-echarts#34]
Any idea how I can get the example to build?
```
D:\3rdparty\purescript-halogen-echarts>npm run example

> @ example D:\3rdparty\purescript-halogen-echarts
> pulp browserify --include example/src --to example/dist/test.js

* Browserifying project in D:\3rdparty\purescript-halogen-echarts
* Building project in D:\3rdparty\purescript-halogen-echarts
* Build successful.
* Browserifying...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'echarts/theme/infographic' from 'D:\3rdparty\purescri
pt-halogen-echarts\output\ECharts.Theme'
    at C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\browser-re
solve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\b
rowser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\bro
wser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\brow
ser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\brow
ser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\me\AppData\Roaming\npm\node_modules\pulp\node_modules\browser-re
solve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ example: `pulp browserify --include example/src --to example/dist/tes
t.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ example script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-03-15T18_04_25_844
Z-debug.log
```

**Comment by cryogenian** [comment]
Looks like you forgot `npm install`

**Comment by Boscop** [comment]
Ah right -.-
Thanks.

**Comment by Boscop** [comment]
Btw, any idea why the example/dist/test.js is 4.5 MB large?
Does it contain the whole echarts lib?
How can I reduce the size? (apart from the usual way to reduce PS output size)
My other huge PS app with lots of functionality (where I want to use echarts) is only 1MB unoptimized currently, and I don't want it to grow by another 4.5 MB just because of echarts.
Is there a way to reduce it?
I only need pie charts, stepped stacked area charts and bar charts, btw.

2. Why does the example work even though it doesn't do this?:
> Please include the echarts-all.js file from echarts via script tag in your html, or concatenate it with the bundled JavaScript file.

**Comment by cryogenian** [comment]
1. Yep, it is echarts.

Ps-echarts uses only few `require`s, I don't think there is simple way of reducing size. Maybe custom echarts build and webpack tuning could help. 

2. Because readme was not updated. Ps-echarts and ps-halogen-echarts take echarts from npm now. Sorry about it.

**Comment by Boscop** [comment]
Thanks.
So does it still use echarts version 2.1.10 (from 2014) or which version?

**Comment by cryogenian** [comment]
The example uses custom fork of 3.5.4. I can verify that there is no any problems with using 4.0.1 since we use it in SlamData. 

Motivation of making cutom fork is that echarts occasionally introduces subtle bugs in its releases. We used to freeze dependency previously, but that time I decided to fix candlestick issue and provide my own build (the fix was merged though %) )

**Comment by Boscop** [comment]
So should I use the official docs for version 3.5.4 or which docs? (Never used echarts before, only google charts..)

Btw, is there an example of a Pie chart (using purescript-halogen-echarts) somewhere?

**Comment by cryogenian** [comment]
Just use `npm install echarts` :)

**Comment by Boscop** [comment]
So when I want to use halogen-echarts outside of the example in my project, should I also do `npm install echarts`?
Or only add it to dev dependencies?

Will it always fetch the right version that is compatible with the version of halogen-echarts used in psc-0.11.7-20180315? Even after a new version of echarts is published on npm?

**Comment by cryogenian** [comment]
Just add it to deps in `package.json`. The main target of this project is to provide bindings to the freshest version of echarts released via npm.

**Comment by Boscop** [comment]
Thanks, everything worked!
